# Defining my base image
FROM python:3.9-slim

# Set the current working directory (CWD) in the container
WORKDIR /app

# Copy content of CWD into /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python3", "app.py"]
